version: "3.8"
services:
  mongodb:
    image: mysql
    container_name: rapid-stock-db
    restart: always
    ports:
      - 8085:27017
    volumes:
      - ./data:/data-mysql
    environment:
      - MYSQL_ROOT_USERNAME=rootuser
      - MYSQL_ROOT_PASSWORD=rootpass
volumes:
  data: {}

networks:
  default:
      name: mysql_network_rd