version: "3.9"
services:
  mariadb:
    image: mariadb
    container_name: rd-stock-maria-db
    ports:
      - 3306:3306
    volumes:
      - ./maria-db/data-mariadb:/var/lib/mysql
      - ./maria-db/sql-export:/sql-export
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/setup.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ../../src/test/resources:/tmp/localstack/test-data
    tmpfs:
      - /tmp/localstack:exec,mode=600