-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 01:40:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rd-stock-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rd-stock-db` ;

-- -----------------------------------------------------
-- Schema rd-stock-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rd-stock-db` DEFAULT CHARACTER SET utf8 ;
USE `rd-stock-db` ;

-- -----------------------------------------------------
-- Table `rd-stock-db`.`OPTION_CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`OPTION_CATEGORIES` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`OPTION_CATEGORIES` (
  `id` DECIMAL(8) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PARENT_PRODUCTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PARENT_PRODUCTS` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PARENT_PRODUCTS` (
  `id` DECIMAL(8) NOT NULL,
  `productId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `productId_UNIQUE` (`productId` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PRODUCT_AVAILABILITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PRODUCT_AVAILABILITIES` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PRODUCT_AVAILABILITIES` (
  `id` BIGINT(8) NOT NULL,
  `companySiteId` VARCHAR(45) NOT NULL,
  `quantityAvailable` DECIMAL(8) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `product_versions_id` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PRODUCT_AVAILABILITIES_PRODUCT_VERSIONS1_idx` (`product_versions_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_AVAILABILITIES_PRODUCT_VERSIONS1`
    FOREIGN KEY (`product_versions_id`)
    REFERENCES `rd-stock-db`.`PRODUCT_VERSIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PRODUCTS_CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PRODUCTS_CATEGORIES` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PRODUCTS_CATEGORIES` (
  `product_id` DECIMAL(8) NOT NULL,
  `category_id` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_PARENT_PRODUCTS_has_OPTION_CATEGORIES_OPTION_CATEGORIES1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_PARENT_PRODUCTS_has_OPTION_CATEGORIES_PARENT_PRODUCTS1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_PARENT_PRODUCTS_has_OPTION_CATEGORIES_PARENT_PRODUCTS1`
    FOREIGN KEY (`product_id`)
    REFERENCES `rd-stock-db`.`PARENT_PRODUCTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARENT_PRODUCTS_has_OPTION_CATEGORIES_OPTION_CATEGORIES1`
    FOREIGN KEY (`category_id`)
    REFERENCES `rd-stock-db`.`OPTION_CATEGORIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PRODUCTS_RACKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PRODUCTS_RACKS` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PRODUCTS_RACKS` (
  `product_id` DECIMAL(8) NOT NULL,
  `rack_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `rack_id`),
  INDEX `fk_PARENT_PRODUCTS_has_RACKS_RACKS1_idx` (`rack_id` ASC) VISIBLE,
  INDEX `fk_PARENT_PRODUCTS_has_RACKS_PARENT_PRODUCTS1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_PARENT_PRODUCTS_has_RACKS_PARENT_PRODUCTS1`
    FOREIGN KEY (`product_id`)
    REFERENCES `rd-stock-db`.`PARENT_PRODUCTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARENT_PRODUCTS_has_RACKS_RACKS1`
    FOREIGN KEY (`rack_id`)
    REFERENCES `rd-stock-db`.`RACKS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PRODUCT_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PRODUCT_TYPES` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PRODUCT_TYPES` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PRODUCT_VERSIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PRODUCT_VERSIONS` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PRODUCT_VERSIONS` (
  `id` DECIMAL(10) NOT NULL,
  `versionId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `price` DECIMAL(10,8) NOT NULL,
  `isAvailable` TINYINT NOT NULL,
  `product_id` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `productId_UNIQUE` (`versionId` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_PRODUCT_VERSIONS_PARENT_PRODUCTS_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_VERSIONS_PARENT_PRODUCTS`
    FOREIGN KEY (`product_id`)
    REFERENCES `rd-stock-db`.`PARENT_PRODUCTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`PRODUCT_VERSIONS_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`PRODUCT_VERSIONS_TYPES` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`PRODUCT_VERSIONS_TYPES` (
  `product_version_id` DECIMAL(10) NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`product_version_id`, `type_id`),
  INDEX `fk_PRODUCT_VERSIONS_has_PRODUCT_TYPES_PRODUCT_TYPES1_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_PRODUCT_VERSIONS_has_PRODUCT_TYPES_PRODUCT_VERSIONS1_idx` (`product_version_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_VERSIONS_has_PRODUCT_TYPES_PRODUCT_VERSIONS1`
    FOREIGN KEY (`product_version_id`)
    REFERENCES `rd-stock-db`.`PRODUCT_VERSIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_VERSIONS_has_PRODUCT_TYPES_PRODUCT_TYPES1`
    FOREIGN KEY (`type_id`)
    REFERENCES `rd-stock-db`.`PRODUCT_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rd-stock-db`.`RACKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rd-stock-db`.`RACKS` ;

CREATE TABLE IF NOT EXISTS `rd-stock-db`.`RACKS` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `parent_rack_id` INT NULL,
  `companyId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RACKS_RACKS1_idx` (`parent_rack_id` ASC) VISIBLE,
  CONSTRAINT `fk_RACKS_RACKS1`
    FOREIGN KEY (`parent_rack_id`)
    REFERENCES `rd-stock-db`.`RACKS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
