version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: rapid-company-db
    ports:
      - 27018:27018
    volumes:
      - ./data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
     image: mongo-express
     container_name: mongo-express-rd
     restart: always
     ports:
       - 8082:8082
     environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
       - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
       - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
      name: mongodb_network_rd