version: "3.9"
services:
  mariadb:
    image: mariadb
    container_name: rd-stock-maria-db
    ports:
      - 3306:3306
    volumes:
      - ./data-mariadb:/var/lib/mysql
      - ./sql-export:/sql-export
    environment:
      MARIADB_ROOT_PASSWORD: qwerty