spring:
  config:
    activate:
      on-profile: decrapted
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  data:
    mongodb:
       authentication-database: admin
       username: rootuser
       password: rootpass
       database: rapid-stock
       port: 27017
       host: localhost
       auto-index-creation: true

---

spring:
  config:
    activate:
      on-profile: rational-db
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: true
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/rd-stock-db
    username: root
    password: qwerty
    driver-class-name: org.mariadb.jdbc.Driver