spring:
  config:
    activate:
      on-profile: local-docker
  autoconfigure.exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  jpa.show-sql: true
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://mariadb:3306/rd_stock_db
    username: root
    password: qwerty
    driver-class-name: org.mariadb.jdbc.Driver

cloud:
  aws:
    localstack.mock-credentials:
      access-key: foobar
      secret-key: foobar
    region:
      static: us-east-1
    stack:
      auto: false
    s3:
      url: http://localstack:4566
      bucket:
        product:
          name: rd-product-version-images
          template-key: company_id=%s/product_id=%d/version_id=%s/