services:
  mariadb:
    image: mariadb
    container_name: rd-stock-maria-db
    ports:
      - "3306:3306"
    volumes:
      - ./maria-db/sql-export/rd_stock_db_creation.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: qwerty

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
