services:
  mariadb:
    image: mariadb
    container_name: rd-stock-maria-db
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./maria-db/sql-export/rd_stock_db_creation.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
    networks:
      - rd_stock_net

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - DEBUG=1
      - TEST_AWS_ACCOUNT_ID=000000000000
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/setup.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./localstack:/var/lib/localstack
    ports:
      - "4566:4566"
    networks:
      - rd_stock_net

  rd-stock:
    container_name: rd-stock
    build:
      context: ../../
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=local-docker

    depends_on:
      localstack:
          condition: service_started
      mariadb:
          condition: service_started
    networks:
      - rd_stock_net

networks:
  rd_stock_net:
    driver: bridge